---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postfix-spool-claim
  namespace: mailserver
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 100Mi
