---

apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh-loadbalancer
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: gitea
  ports:
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: gitea-ssh
