---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
spec:
  nfs:
    server: 10.0.0.5
    path: "/mnt/nfs_share"
    readOnly: false
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
