---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    service: server-claim1
  name: server-claim1
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 100Mi
