---

apiVersion: v1
kind: Pod
metadata:
  name: shellshockable-ssh-pod
  labels:
    app: shellshockable-ssh
spec:
  containers:
    - name: shellshockable-ssh
      image: tbellus/shellshockable
      ports:
        - containerPort: 22
          name: ss-ssh
