---

apiVersion: v1
kind: Service
metadata:
  name: shellshockable-ssh-loadbalancer
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  selector:
    app: shellshockable-ssh
  ports:
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: ss-ssh
